name: Frontend CI/CD - Deploy Vite to EC2 (Manual Build)

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy-frontend:
    name: Deploy Manually Built Vite App to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Upload Pre-built App to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          source: "dist/*"
          target: "/tmp/vite-deploy"

      - name: Activate New Build (Blue-Green)
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          script: |
            sudo rm -rf /var/www/html-old
            if [ -d /var/www/html ]; then
              sudo mv /var/www/html /var/www/html-old
            fi
            sudo mv /tmp/vite-deploy /var/www/html
            sudo systemctl restart nginx
            echo "✅ Deployed manually built Vite app"

      - name: Rollback Instructions
        run: |
          echo "To rollback, SSH into EC2 and run:"
          echo "sudo rm -rf /var/www/html"
          echo "sudo cp -r /var/www/html-old /var/www/html"
          echo "sudo systemctl restart nginx"

